# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Layer Music Project
email: layer@layermusicproject.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going to make a material design theme next!
baseurl: "" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: ""
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: 
authorBio: A musician by night.
