OB# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Layer Music Project
email: layer@layermusicproject.com
description: CHECK LAYER OUT IF YOU LIKE ELECTRONICA TRACKS THAT BUILD INTO ONE BIG CRESCENDO TOWARDS THE END!
baseurl: "" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: ""
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: http://bit.ly/layertwitter
facebook: http://bit.ly/layerfb
youtube: http://bit.ly/layerb

author: 
authorBio: Chaitanya Bulusu ( Chatty) and his work transcends genre and style – instead focusing more on swing, melody, vibe and atmosphere.
